import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header/Header";
import MobileHeader from "./Components/Header/MobileHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NDVP-SME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="2xl:block hidden">
          <Header />
        </div>
        <div className="2xl:hidden block">
          <MobileHeader />
        </div>
        {children}
      </body>
    </html>
  );
}
